# Generated by Django 4.2.20 on 2026-04-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_user_alter_friendslist_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_stop', to='routes.location', verbose_name='Позиция остановки'),
        ),
    ]
