# Generated by Django 4.2.20 on 2026-05-17 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_stop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['start__time'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.RemoveField(
            model_name='route',
            name='date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='time',
        ),
        migrations.AlterField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
